server {
    listen 80 default;
    server_name _;

    client_max_body_size 108M;

    # Don't allow direct access to arbitrary *.php paths
    location ~ \.php$ { return 404; }

    access_log /var/log/nginx/application.access.log;
    error_log /var/log/nginx/application.error.log;

    root /application/public/static;

    #### Home
    location = / {
        index pages/home/index.html;
    }

    #### About
    location = /about {
        alias /application/public/static/pages/about/index.html;
        default_type text/html;
    }

    #### Projects
    location = /projects {
        alias /application/public/static/pages/projects/index.html;
        default_type text/html;
    }

    #### Blog
    location ^~ /blog {
        # serve blog_temp.html for all /blog/ requests for now, until we have the grav container set up
        try_files /pages/blog_temp.html =404;
        default_type text/html;
    }

    #### Static assets (css, js, images, etc.)
    location /static/ {
        alias /application/public/static/;
        try_files $uri =404;
    }
}